# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0bd2dce2a352f2ca10d389a2096484fba64e3c37bcc1fc7698d20fbd54a8b0d17b3fa9a439661cc3c2cd55535fe38860b3adf6610664a4fbc8a094e5846481ad

test:
  secret_key_base: 7cce2b9b61dffe0e71029553e7100ea800226d066d86867170bdd12f34bf2a96e7c8ac46a44ecfde81cb61c62d2601e5bffcb9579a687065a1d7255bca3453e2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
